### ISSUE TITLE
set up GitHub pages for this repo to make the documentation link work

### ISSUE THREAD

**Issue by xianqiliu** [amadeus4dev-examples/amadeus-php#93]
@jabrena @tsolakoua @minjikarin hey, although I saw the warning that the Amadeus for Developers team will not support or maintain this SDK, however, since this repo has been transferred to another organization, which means the URL for the PHP documentation should be changed too. Thus, please set up GitHub pages for this repo to make the documentation link works again. (Cuz only the admin user of this organization can set up GitHub pages so I can't contribute to it, you can see more details [here](https://docs.github.com/en/pages))
https://github.com/amadeus4dev-examples/amadeus-php/blob/2f09497cf4df068de86eda43cc716478412ce1a9/README.md?plain=1#L136
In addition, the link in the place shown below should also be changed.
![image](https://user-images.githubusercontent.com/74473717/191046126-5164c3f0-bfd2-489a-990c-2ee32d77b6c1.png)

**Comment by xianqiliu** [comment]
@jabrena @tsolakoua @minjikarin really hope this issue could be fixed ASAP, please! thank you :)

**Comment by xianqiliu** [comment]
@tsolakoua Nice! Just a reminder for next time, I think the best practice is to create a PR from your forked repo. Cuz every time you create a branch from the original repo, it will be also automatically updated on Packagist as shown below.
![image](https://user-images.githubusercontent.com/74473717/191081981-b14de01c-3618-4c89-94de-7da0a1a3ac3b.png)

**Comment by tsolakoua** [comment]
That's true!!! Thanks @xianqiliu for the reminder! I deleted the additional packages created by the PRs.
